title: My Hugo
theme: van
languageCode: en-us
hasCJKLanguage: true
metaDataFormat: yaml
defaultContentLanguage: en
pygmentsCodeFences: true
pygmentsUseClasses: true
markup:
  goldmark:
    renderer:
      unsafe: true