languageCode: "en-us"
title: "jzou"
theme: van

hasCJKLanguage: true
metaDataFormat: "yaml"

pygmentsUseClasses: true
pygmentsCodefences: true

defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: false

markup:
  goldmark:
    renderer:
      unsafe: true
      